import { useEffect, useMemo, useState } from "react";
import { getDashboardMetrics } from "../api/dashboardApi";
import { getNotifications, updateNotification } from "../api/notificationApi";
import { fetchRecommendations } from "../api/recommendationApi";

const nav = [["Dashboard","/admin","▦"],["Rooms","/admin/rooms","♙"],["Tenants","/admin/tenants","♧"],["Billing","/billing","▣"],["Customer Requests","/customer-requests","□"],["Analytics & Reports","/analytics","⌑"]];
const value = (data, ...keys) => keys.map((key) => data?.[key]).find((item) => item !== undefined) ?? 0;

export default function AdminDashboard() {
  const [metrics, setMetrics] = useState({}); const [notifications, setNotifications] = useState([]); const [recommendations, setRecommendations] = useState([]); const [error, setError] = useState("");
  const [notificationsOpen, setNotificationsOpen] = useState(false); const [accountOpen, setAccountOpen] = useState(false);
  const user = useMemo(() => { try { return JSON.parse(localStorage.getItem("user") || "null") || {}; } catch { return {}; } }, []);
  useEffect(() => { Promise.allSettled([getDashboardMetrics(), getNotifications(), fetchRecommendations()]).then(([m,n,r]) => { if(m.status === "fulfilled") setMetrics(m.value || {}); if(n.status === "fulfilled") setNotifications(n.value || []); if(r.status === "fulfilled") setRecommendations(r.value || []); if([m,n,r].every((item) => item.status === "rejected")) setError("Dashboard data could not be loaded."); }); }, []);
  const logout = () => { localStorage.clear(); window.location.assign("/"); };
  const markRead = async (id) => { await updateNotification(id); setNotifications((items) => items.map((item) => item.id === id ? { ...item, is_read: true, status: "Read" } : item)); };
  const cards = [["Monthly Revenue",value(metrics,"monthlyRevenue","collectedRevenue"),"₱","green"],["Occupancy Rate",value(metrics,"occupancy","occupancyRate"),"▥","blue"],["Active Tenants",value(metrics,"activeTenants","totalTenants"),"♧","blue"],["Late Payments",value(metrics,"latePayments"),"△","red"]];
  return <div className="admin-shell"><aside className="admin-side"><a href="/admin" className="admin-brand"><b>▥</b><span><strong>Spartment</strong><small>Apartment OS</small></span></a><p>Manage</p><nav>{nav.map(([label,href,icon]) => <a className={label === "Dashboard" ? "active" : ""} href={href} key={label}><i>{icon}</i>{label}</a>)}</nav></aside>
    <div className="admin-work"><header className="admin-top"><div className="admin-top-menu"><button className="admin-notice-button" aria-label="Admin notifications" aria-expanded={notificationsOpen} onClick={() => { setNotificationsOpen((value) => !value); setAccountOpen(false); }}>♧{notifications.some((n) => n.status === "Unread" || n.is_read === false) && <i />}</button>{notificationsOpen && <section className="admin-notification-dropdown"><header><div><h3>Notifications</h3><small>{notifications.filter((n) => n.status === "Unread" || n.is_read === false).length} unread</small></div><a href="/admin/notifications">View all</a></header>{notifications.length ? <ul>{notifications.slice(0,5).map((item) => { const unread = item.status === "Unread" || item.is_read === false; return <li className={unread ? "unread" : ""} key={item.id}><div><strong>{item.title || item.type || "Notification"}</strong><p>{item.message}</p></div>{unread && <button type="button" onClick={() => markRead(item.id)}>Mark read</button>}</li>; })}</ul> : <p className="admin-empty">No notifications yet.</p>}</section>}</div><span className="admin-avatar">{(user.name || "Admin")[0]}</span><div className="admin-top-menu"><button className="admin-user" aria-label="Open admin account menu" aria-expanded={accountOpen} onClick={() => { setAccountOpen((value) => !value); setNotificationsOpen(false); }}><strong>{user.name || "Admin"}</strong><small>Admin</small></button>{accountOpen && <div className="admin-account-dropdown"><strong>{user.email || "admin.demo@spartment.local"}</strong><button type="button" onClick={logout}>↪ <span>Log out</span></button></div>}</div></header>
      <main className="admin-main"><div className="admin-title"><div><h1>Dashboard</h1><p>Overview, notifications &amp; recommendations.</p></div><a href="/analytics">Open Analytics <span>→</span></a></div>{error && <p role="alert">{error}</p>}
        <section className="admin-kpis">{cards.map(([label,number,icon,tone]) => <article key={label}><i className={tone}>{icon}</i><p>{label}</p><strong>{typeof number === "number" && label === "Monthly Revenue" ? `₱${number.toLocaleString()}` : number}</strong></article>)}</section>
        <div className="admin-panels"><section className="admin-panel"><header><h2>♧ &nbsp;Notifications</h2><span>{notifications.filter((n) => n.status === "Unread" || n.is_read === false).length} new</span></header>{notifications.length ? <ul className="admin-feed">{notifications.slice(0,5).map((item) => <li key={item.id}><i className="blue">{(item.category || item.type)?.[0] || "N"}</i><div><strong>{item.title || item.category || item.type || "Notification"}</strong><p>{item.message}</p></div></li>)}</ul> : <p className="admin-empty">No notifications yet.</p>}</section>
          <section className="admin-panel"><header><div><h2>Smart Recommendations</h2><p>Suggested actions to improve operations</p></div></header><div className="admin-recs">{recommendations.length ? recommendations.slice(0,4).map((item,index) => <article className={(item.priority || ["High","Medium","Low"][index%3]).toLowerCase()} key={item.id || index}><strong>{item.title || item.category || "Recommendation"}</strong><p>{item.description || item.message || item.risk_condition}</p></article>) : <p className="admin-empty">No active recommendations.</p>}</div></section></div>
      </main></div></div>;
}
