import { useEffect, useMemo, useState } from "react";
import { createRoom, getRooms, updateRoom } from "../api/roomApi";
import { getTenants } from "../api/tenantApi";
import { getNotifications, updateNotification } from "../api/notificationApi";

const nav = [["Dashboard","/admin","▦"],["Rooms","/admin/rooms","♙"],["Tenants","/admin/tenants","♧"],["Billing","/billing","▣"],["Customer Requests","/customer-requests","□"],["Analytics & Reports","/analytics","⌑"]];
const numberOf = (room) => room.room_number || room.roomNumber || "—";
const rentOf = (room) => Number(room.monthly_rent ?? room.monthlyRent ?? 0);
const floorOf = (room) => Number(String(numberOf(room)).charAt(0)) || 1;
const tenantRoom = (tenant) => tenant.room_id || tenant.roomId || tenant.room?.id;
const emptyRoom = { roomNumber: "", roomType: "Standard", description: "", monthlyRent: "6500", status: "Available" };

export default function AdminRooms() {
  const [rooms,setRooms]=useState([]), [tenants,setTenants]=useState([]), [notifications,setNotifications]=useState([]);
  const [loading,setLoading]=useState(true), [error,setError]=useState(""), [editing,setEditing]=useState(null), [adding,setAdding]=useState(false);
  const [form,setForm]=useState(emptyRoom), [noticeOpen,setNoticeOpen]=useState(false), [accountOpen,setAccountOpen]=useState(false);
  const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem("user")||"null")||{};}catch{return {};}},[]);
  const load=async()=>{setLoading(true);setError("");try{const [roomResult,tenantResult,noticeResult]=await Promise.all([getRooms(),getTenants(),getNotifications()]);setRooms(Array.isArray(roomResult)?roomResult:roomResult.data||[]);setTenants(Array.isArray(tenantResult)?tenantResult:tenantResult.data||[]);setNotifications(noticeResult||[]);}catch(reason){setError(reason.message);}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const groups=useMemo(()=>Object.entries(rooms.reduce((all,room)=>{(all[floorOf(room)]??=[]).push(room);return all;},{})).sort(([a],[b])=>a-b),[rooms]);
  const tenantFor=(room)=>tenants.find((tenant)=>tenantRoom(tenant)===room.id&&String(tenant.status).toLowerCase()==="active");
  const average=rooms.length?Math.round(rooms.reduce((sum,room)=>sum+rentOf(room),0)/rooms.length):0;
  const openEdit=(room)=>{setEditing(room);setForm({status:room.status,monthlyRent:String(rentOf(room))});};
  const submit=async(event)=>{event.preventDefault();setError("");try{if(editing)await updateRoom(editing.id,{status:form.status,monthlyRent:Number(form.monthlyRent)});else await createRoom({...form,monthlyRent:Number(form.monthlyRent)});setEditing(null);setAdding(false);setForm(emptyRoom);await load();}catch(reason){setError(reason.message);}};
  const markRead=async(id)=>{await updateNotification(id);setNotifications((items)=>items.map((item)=>item.id===id?{...item,is_read:true,status:"Read"}:item));};
  const logout=()=>{localStorage.removeItem("token");localStorage.removeItem("user");localStorage.removeItem("tenantId");window.location.assign("/");};
  const unread=(item)=>item.is_read===false||item.status==="Unread";
  return <div className="admin-shell"><aside className="admin-side"><a href="/admin" className="admin-brand"><b>▥</b><span><strong>Spartment</strong><small>Apartment OS</small></span></a><p>Manage</p><nav>{nav.map(([label,href,icon])=><a className={label==="Rooms"?"active":""} href={href} key={label}><i>{icon}</i>{label}</a>)}</nav></aside><div className="admin-work">
    <header className="admin-top"><div className="admin-top-menu"><button className="admin-notice-button" aria-label="Admin notifications" onClick={()=>{setNoticeOpen(!noticeOpen);setAccountOpen(false);}}>♧{notifications.some(unread)&&<i/>}</button>{noticeOpen&&<section className="admin-notification-dropdown"><header><h3>Notifications</h3><a href="/admin/notifications">View all</a></header>{notifications.length?<ul>{notifications.slice(0,5).map((item)=><li className={unread(item)?"unread":""} key={item.id}><div><strong>{item.title||item.type}</strong><p>{item.message}</p></div>{unread(item)&&<button onClick={()=>markRead(item.id)}>Mark read</button>}</li>)}</ul>:<p className="admin-empty">No notifications yet.</p>}</section>}</div><span className="admin-avatar">{(user.name||"Admin")[0]}</span><div className="admin-top-menu"><button className="admin-user" onClick={()=>{setAccountOpen(!accountOpen);setNoticeOpen(false);}}><strong>{user.name||"Admin"}</strong><small>Admin</small></button>{accountOpen&&<div className="admin-account-dropdown"><strong>{user.email}</strong><button onClick={logout}>↪ <span>Log out</span></button></div>}</div></header>
    <main className="admin-main"><div className="admin-title"><div><h1>Rooms</h1><p>{rooms.length} rooms · {groups.length} floors · ₱{average.toLocaleString()}/month average</p></div><button className="admin-add-room" onClick={()=>{setAdding(true);setForm(emptyRoom);}}>＋ Add Room</button></div>{error&&<p className="rooms-error" role="alert">{error}<button onClick={load}>Try again</button></p>}{loading?<p>Loading rooms…</p>:groups.map(([floor,list])=><section className="admin-room-floor" key={floor}><header><h2>Floor {floor}</h2><div className="admin-room-legend"><span className="available">● Vacant</span><span className="occupied">● Occupied</span><span className="reserved">● Reserved</span><span className="maintenance">● Maintenance</span></div></header><div className="admin-room-grid">{list.map((room)=>{const tenant=tenantFor(room),status=String(room.status).toLowerCase();return <article className={`admin-room-card ${status}`} key={room.id}><div><h3>{numberOf(room)}</h3><span className={`room-badge room-badge--${status}`}><i/>{status==="available"?"Vacant":room.status}</span></div><small>Floor {floor}</small><p className="admin-room-tenant">{tenant?`♙ ${tenant.full_name||tenant.name}`:<em>Unassigned</em>}</p><footer><strong>₱{rentOf(room).toLocaleString()}<small>/mo</small></strong><button onClick={()=>openEdit(room)}>✎ Edit</button></footer></article>;})}</div></section>)}</main></div>
    {(adding||editing)&&<div className="room-editor-backdrop"><form className="room-editor" role="dialog" aria-label={editing?`Edit room ${numberOf(editing)}`:"Add room"} onSubmit={submit}><header><h2>{editing?`Edit Room ${numberOf(editing)}`:"Add Room"}</h2><button type="button" aria-label="Close" onClick={()=>{setAdding(false);setEditing(null);}}>×</button></header>{!editing&&<><label>Room Number<input required value={form.roomNumber} onChange={(e)=>setForm({...form,roomNumber:e.target.value})}/></label><label>Room Type<input required value={form.roomType} onChange={(e)=>setForm({...form,roomType:e.target.value})}/></label><label>Description<input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label></>}<label>Status<select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}>{["Available","Occupied","Reserved","Maintenance"].map(value=><option key={value}>{value}</option>)}</select></label><label>Monthly Rent (₱)<input required type="number" min="0" value={form.monthlyRent} onChange={(e)=>setForm({...form,monthlyRent:e.target.value})}/></label><footer><button type="button" onClick={()=>{setAdding(false);setEditing(null);}}>Cancel</button><button type="submit">{editing?"Save changes":"Add room"}</button></footer></form></div>}
  </div>;
}
