import { useEffect, useState } from "react";
import { getTenants } from "../api/tenantApi";
import { getRooms } from "../api/roomApi";
import { getInquiries } from "../api/inquiryApi";
import { createTenant } from "../api/tenantCreationApi";
import { getNotifications, updateNotification } from "../api/notificationApi";

const nav = [["Dashboard","/admin","▦"],["Rooms","/admin/rooms","♙"],["Tenants","/admin/tenants","♧"],["Billing","/billing","▣"],["Customer Requests","/customer-requests","□"],["Analytics & Reports","/analytics","⌑"]];
const blank = { inquiryId:"", fullName:"", email:"", contact:"", roomId:"", username:"", password:"" };
const rows = (result) => Array.isArray(result) ? result : result?.data || [];
const roomNumber = (room) => room?.room_number || room?.roomNumber || "—";
const roomRent = (room) => Number(room?.monthly_rent ?? room?.monthlyRent ?? 0);
const tenantName = (tenant) => tenant.full_name || tenant.fullName || tenant.name || tenant.user?.name || "Tenant";
const tenantEmail = (tenant) => tenant.email || tenant.user?.email || "No email";

export default function AdminTenants() {
  const [tenants,setTenants]=useState([]), [rooms,setRooms]=useState([]), [inquiries,setInquiries]=useState([]), [notifications,setNotifications]=useState([]);
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState(""), [created,setCreated]=useState(null);
  const [adding,setAdding]=useState(false), [form,setForm]=useState(blank), [noticeOpen,setNoticeOpen]=useState(false), [accountOpen,setAccountOpen]=useState(false);
  const [user]=useState(()=>{try{return JSON.parse(localStorage.getItem("user")||"null")||{};}catch{return {};}});
  const load=async()=>{setLoading(true);setError("");try{const [tenantResult,roomResult,inquiryResult,noticeResult]=await Promise.all([getTenants(),getRooms(),getInquiries(),getNotifications()]);setTenants(rows(tenantResult));setRooms(rows(roomResult));setInquiries(rows(inquiryResult));setNotifications(rows(noticeResult));}catch(reason){setError(reason.message);}finally{setLoading(false);}};
  // Loading from the backend is the page's initial external synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load();},[]);
  const activeTenants=tenants.filter((tenant)=>String(tenant.status||"Active").toLowerCase()==="active");
  const availableRooms=rooms.filter((room)=>["available","vacant"].includes(String(room.status).toLowerCase()));
  const approvedInquiries=inquiries.filter((inquiry)=>String(inquiry.status).toLowerCase()==="approved"&&!tenants.some((tenant)=>(tenant.inquiry_id||tenant.inquiry?.id)===(inquiry.id)));
  const chooseInquiry=(id)=>{const inquiry=approvedInquiries.find((item)=>item.id===id);setForm({...form,inquiryId:id,fullName:inquiry?.full_name||inquiry?.fullName||inquiry?.name||"",email:inquiry?.email||"",contact:inquiry?.contact||"",roomId:inquiry?.room_id||inquiry?.roomId||inquiry?.room?.id||form.roomId,username:(inquiry?.email||"").split("@")[0]});};
  const submit=async(event)=>{event.preventDefault();setSaving(true);setError("");try{const result=await createTenant(form);setCreated(result?.data?.credentials||result?.credentials||null);setAdding(false);setForm(blank);await load();}catch(reason){setError(reason.message);}finally{setSaving(false);}};
  const markRead=async(id)=>{await updateNotification(id);setNotifications((items)=>items.map((item)=>item.id===id?{...item,is_read:true,status:"Read"}:item));};
  const unread=(item)=>item.is_read===false||item.status==="Unread";
  const logout=()=>{localStorage.removeItem("token");localStorage.removeItem("user");localStorage.removeItem("tenantId");window.location.assign("/");};
  return <div className="admin-shell"><aside className="admin-side"><a href="/admin" className="admin-brand"><b>▥</b><span><strong>Spartment</strong><small>Apartment OS</small></span></a><p>Manage</p><nav>{nav.map(([label,href,icon])=><a className={label==="Tenants"?"active":""} href={href} key={label}><i>{icon}</i>{label}</a>)}</nav></aside><div className="admin-work">
    <header className="admin-top"><div className="admin-top-menu"><button className="admin-notice-button" aria-label="Admin notifications" onClick={()=>{setNoticeOpen(!noticeOpen);setAccountOpen(false);}}>♧{notifications.some(unread)&&<i/>}</button>{noticeOpen&&<section className="admin-notification-dropdown"><header><h3>Notifications</h3><a href="/admin/notifications">View all</a></header>{notifications.length?<ul>{notifications.slice(0,5).map((item)=><li className={unread(item)?"unread":""} key={item.id}><div><strong>{item.title||item.type}</strong><p>{item.message}</p></div>{unread(item)&&<button onClick={()=>markRead(item.id)}>Mark read</button>}</li>)}</ul>:<p className="admin-empty">No notifications yet.</p>}</section>}</div><span className="admin-avatar">{(user.name||"Admin")[0]}</span><div className="admin-top-menu"><button className="admin-user" onClick={()=>{setAccountOpen(!accountOpen);setNoticeOpen(false);}}><strong>{user.name||"Admin"}</strong><small>Admin</small></button>{accountOpen&&<div className="admin-account-dropdown"><strong>{user.email}</strong><button onClick={logout}>↪ <span>Log out</span></button></div>}</div></header>
    <main className="admin-main"><div className="admin-title"><div><h1>Tenants</h1><p>{activeTenants.length} active tenant{activeTenants.length===1?"":"s"}</p></div><button className="admin-add-room" onClick={()=>{setAdding(true);setCreated(null);setForm(blank);}}>＋ Add Tenant</button></div>{error&&<p className="rooms-error" role="alert">{error}<button onClick={load}>Try again</button></p>}{created&&<p className="tenant-created" role="status">Tenant created. Username: <strong>{created.username}</strong>{created.password&&<> · Password: <strong>{created.password}</strong></>}</p>}{loading?<p>Loading tenants…</p>:<div className="admin-tenant-grid">{tenants.map((tenant)=>{const room=tenant.room||rooms.find((item)=>item.id===(tenant.room_id||tenant.roomId));return <article className="admin-tenant-card" key={tenant.id}><div className="tenant-card-head"><span>{tenantName(tenant)[0]}</span><div><h2>{tenantName(tenant)}</h2><p>{tenantEmail(tenant)}</p></div><em>● {tenant.status||"Active"}</em></div><div className="tenant-card-facts"><p><small>Room</small><strong>{roomNumber(room)}</strong></p><p><small>Rent</small><strong>₱{roomRent(room).toLocaleString()}</strong></p></div><footer><a href={`/tenant-details?id=${tenant.id}`}>✎ View</a><a href={`mailto:${tenantEmail(tenant)}`}>□ Contact</a></footer></article>;})}</div>}</main></div>
    {adding&&<div className="room-editor-backdrop"><form className="room-editor tenant-editor" role="dialog" aria-label="Add tenant" onSubmit={submit}><header><div><h2>Add Tenant</h2><p>Create an account from an approved inquiry.</p></div><button type="button" aria-label="Close" onClick={()=>setAdding(false)}>×</button></header><label>Approved Inquiry<select required value={form.inquiryId} onChange={(e)=>chooseInquiry(e.target.value)}><option value="">Select an approved inquiry</option>{approvedInquiries.map((item)=><option value={item.id} key={item.id}>{item.full_name||item.name||item.email}</option>)}</select></label>{approvedInquiries.length===0&&<p className="tenant-form-note">No unused approved inquiries are available. Approve one in Customer Requests first.</p>}<label>Full Name<input required value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label>Contact<input value={form.contact} onChange={(e)=>setForm({...form,contact:e.target.value})}/></label><label>Assigned Room<select required value={form.roomId} onChange={(e)=>setForm({...form,roomId:e.target.value})}><option value="">Select an available room</option>{availableRooms.map((room)=><option value={room.id} key={room.id}>Room {roomNumber(room)} — ₱{roomRent(room).toLocaleString()}</option>)}</select></label><label>Username<input required value={form.username} onChange={(e)=>setForm({...form,username:e.target.value})}/></label><label>Default Password<input required minLength="8" type="password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/></label><footer><button type="button" onClick={()=>setAdding(false)}>Cancel</button><button type="submit" disabled={saving||!approvedInquiries.length}>{saving?"Creating…":"Create Tenant"}</button></footer></form></div>}
  </div>;
}
