import { supabase } from "../config/supabaseClient.js";

/*
|--------------------------------------------------------------------------
| Authentication Model
|--------------------------------------------------------------------------
| Database operations for user authentication.
|
| Password comparison and JWT generation belong in authService.js.
|--------------------------------------------------------------------------
*/

/*
|--------------------------------------------------------------------------
| Get User by Email
|--------------------------------------------------------------------------
*/

export async function getUserByEmail(email) {
  if (!email) {
    return null;
  }

  const normalizedEmail = String(email)
    .trim()
    .toLowerCase();

  const { data, error } = await supabase
    .from("users")
    .select(`
      id,
      name,
      email,
      username,
      password_hash,
      role,
      status,
      created_at,
      updated_at
    `)
    .ilike("email", normalizedEmail)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to retrieve user: ${error.message}`,
    );
  }

  return data;
}

/*
|--------------------------------------------------------------------------
| Get User by Username
|--------------------------------------------------------------------------
*/

export async function getUserByUsername(username) {
  if (!username) {
    return null;
  }

  const normalizedUsername = String(username).trim();

  const { data, error } = await supabase
    .from("users")
    .select(`
      id,
      name,
      email,
      username,
      password_hash,
      role,
      status,
      created_at,
      updated_at
    `)
    .ilike("username", normalizedUsername)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to retrieve user: ${error.message}`,
    );
  }

  return data;
}

/*
|--------------------------------------------------------------------------
| Get User by Email or Username
|--------------------------------------------------------------------------
*/

export async function getUserByIdentifier(identifier) {
  if (!identifier) {
    return null;
  }

  const normalizedIdentifier =
    String(identifier).trim();

  const userByEmail =
    await getUserByEmail(normalizedIdentifier);

  if (userByEmail) {
    return userByEmail;
  }

  return getUserByUsername(normalizedIdentifier);
}

/*
|--------------------------------------------------------------------------
| Get User by ID
|--------------------------------------------------------------------------
*/

export async function getUserById(userId) {
  if (!userId) {
    return null;
  }

  const { data, error } = await supabase
    .from("users")
    .select(`
      id,
      name,
      email,
      username,
      role,
      status,
      created_at,
      updated_at
    `)
    .eq("id", userId)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to retrieve user: ${error.message}`,
    );
  }

  return data;
}

/*
|--------------------------------------------------------------------------
| Create User
|--------------------------------------------------------------------------
| passwordHash must already be generated by the service.
|--------------------------------------------------------------------------
*/

export async function createUserRecord({
  name,
  email,
  username = null,
  passwordHash,
  role = "tenant",
  status = "Active",
}) {
  const { data, error } = await supabase
    .from("users")
    .insert({
      name: String(name).trim(),
      email: String(email).trim().toLowerCase(),
      username: username
        ? String(username).trim()
        : null,
      password_hash: passwordHash,
      role,
      status,
    })
    .select(`
      id,
      name,
      email,
      username,
      role,
      status,
      created_at,
      updated_at
    `)
    .single();

  if (error) {
    if (error.code === "23505") {
      throw new Error(
        "A user with this email or username already exists",
      );
    }

    throw new Error(
      `Failed to create user: ${error.message}`,
    );
  }

  return data;
}

/*
|--------------------------------------------------------------------------
| Update User Password Hash
|--------------------------------------------------------------------------
*/

export async function updateUserPasswordHash(
  userId,
  passwordHash,
) {
  const { data, error } = await supabase
    .from("users")
    .update({
      password_hash: passwordHash,
    })
    .eq("id", userId)
    .select(`
      id,
      name,
      email,
      username,
      role,
      status,
      updated_at
    `)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to update password: ${error.message}`,
    );
  }

  return data;
}